---
dist: xenial
language: python
python:
  - "3.7"

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

install:
  - source $HOME/.poetry/env
  - poetry install

script:
  - poetry run flake8 lambda_mongo_utils tests
  - poetry run pytest --cov=lambda_mongo_utils tests/
